# Generated by Django 4.2 on 2025-01-31 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('user_role_choice', models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('GUIDE', 'Guide'), ('ADMIN', 'Admin')], max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_info.course')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_info.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_group_role_choice', models.CharField(blank=True, choices=[('MEMBER', 'Member'), ('LEADER', 'Leader')], max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.users')),
            ],
        ),
    ]
