# Generated by Django 4.2 on 2025-03-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_role_choice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
