# Generated by Django 4.2 on 2025-03-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_users_user_role_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_groups',
            name='student_group_role_choice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
