# Generated by Django 4.2 on 2025-03-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_student_groups_student_group_role_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/no_profile_pic.webp', null=True, upload_to='profile_pictures/'),
        ),
    ]
