# Generated by Django 4.2 on 2025-04-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_users_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_groups',
            name='student_group_role_choice',
        ),
        migrations.AddField(
            model_name='student_groups',
            name='student_group_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/no_profile_pic.webp', null=True, upload_to='static/images/profile_pictures/'),
        ),
    ]
