# Generated by Django 4.2 on 2025-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_student_groups_student_group_role_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
