# Generated by Django 4.2 on 2025-05-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_users_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_role_choice',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20, null=True),
        ),
    ]
