# Generated by Django 4.2 on 2025-05-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_users_user_role_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_role_choice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
