# Generated by Django 4.2 on 2025-01-31 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract_title', models.CharField(blank=True, max_length=30, null=True)),
                ('abstract_path', models.CharField(blank=True, max_length=100, null=True)),
                ('guide_message', models.CharField(blank=True, max_length=500, null=True)),
                ('rank', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.student_groups')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('NOT_SUBMITTED', 'Not Submitted'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], max_length=16, null=True)),
                ('review_choices', models.CharField(blank=True, choices=[('ABSTRACT', 'Abstract'), ('REVIEW_1', 'Review 1'), ('REVIEW_2', 'Review 2'), ('REVIEW_3', 'Review 3'), ('REVIEW_4', 'Review 4')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('abstract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_info.abstract')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.users')),
            ],
        ),
    ]
