# Generated by Django 4.2 on 2025-02-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
