# Generated by Django 4.2 on 2025-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_info', '0002_alter_abstract_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstract',
            old_name='abstract_path',
            new_name='abstract_file_name',
        ),
        migrations.AddField(
            model_name='abstract',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project_reviews',
            name='project_status',
            field=models.CharField(blank=True, choices=[('NOT_SUBMITTED', 'Not Submitted'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], default='NOT_SUBMITTED', max_length=16, null=True),
        ),
    ]
