# Generated by Django 4.2 on 2025-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_info', '0003_rename_abstract_path_abstract_abstract_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_reviews',
            name='project_status',
            field=models.CharField(blank=True, default='NOT_SUBMITTED', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='project_reviews',
            name='review_choices',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
