# Generated by Django 4.2 on 2025-05-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_info', '0005_abstract_abstract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='guide_messageto_hod',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='hod_messageto_guide',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
