# Generated by Django 4.2 on 2025-05-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_info', '0006_abstract_guide_messageto_hod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='clarity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='feasibility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='methodology',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='originality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='presentation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='abstract_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
